insert into T_PAYMENT_THRESHOLD values ('ROSHAN', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('AMC', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('OOREDOO (WATANIYA)', 50, 'SDR', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('UNITEL', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('CLARO', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('U COM', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('OPTUS SINGTEL', 85, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('TELSTRA', 80, 'SDR', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('A1 TELEKOM', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('HUTCHISON (ORANGE MERGED)', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('T-MOBILE', 50, 'USD', 'per SIM ');
insert into T_PAYMENT_THRESHOLD values ('AKTEL (AXIATA)', 50, 'SDR', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('MTS', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('VELCOM', 75, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('BASE NV/SA', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('BMOBILE', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('VIVO', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('DST', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('GLOBUL -TELENOR', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('MOBITEL', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('CADCOMMS', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('CELLCARD', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('SMART', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('VIETTEL', 65, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('ROGERS', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('SASKTEL', 50, 'USD', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('VIDEOTRON', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('MOOV', 80, 'USD', 'total SIM ');
insert into T_PAYMENT_THRESHOLD values ('CHINA MOBILE', 80, 'USD', 'per PLMN');
insert into T_PAYMENT_THRESHOLD values ('CHINA UNICOM', 80, 'USD', 'per PLMN');
insert into T_PAYMENT_THRESHOLD values ('ICE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIPNET', 90, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CYTAMOBILE VODAFONE', 80, 'USD', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('PRIMETEL', 80, 'USD', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA O2', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('T-MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CLARO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('GREENCOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ELISA', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ALANDS MOBILTELEFON AB', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('BOUYGUES TELECOM', 60, 'EUR', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('FREE MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SFR', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MOBITEL (BEELINE)', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('E PLUS', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA O2', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VODAFONE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('WIND HELLAS', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CHINA MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CSL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AIRTEL , BHARTI', 40, 'USD', 'per PLMN');
insert into T_PAYMENT_THRESHOLD values ('VODAFONE', 560, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AXIS', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('HUTCHISON', 50, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('IRANCELL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('RIGHTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ZAIN', 80, 'USD', 'per PLMN');
insert into T_PAYMENT_THRESHOLD values ('PELEPHONE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('HUTCHISON 3G', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TIM', 80, 'USD', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('WIND', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('DIGICEL', 80, 'USD', 'per SIM');
insert into T_PAYMENT_THRESHOLD values ('KDDI', 80, 'SDR', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VODAFONE AIRTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ALTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('KARTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTC (ZAIN)', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIVA', 55, 'SDR', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MEGACOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('LATVIAN MOBILE TELEPHONE CO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTC (TOUCH)', 80, 'SDR', 'nan');
insert into T_PAYMENT_THRESHOLD values ('CELLCOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEKOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TANGO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CTM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIP OPERATOR', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CELCOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('DIGI', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MAXIS', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('U MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('GO MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTML', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELCEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MONAC TELECOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('M:TEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MEDI TELECOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('M CEL', 50, 'SDR ', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MPT', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('OOREDOO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('N CELL', 80, 'SDR ', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('2 DEGREE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTN', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('OMANTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('WATANIYA', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('DIGITEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('GLOBE TELECOM', 100, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SMART', 80, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('ORANGE (PTK CENTERTEL)', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('P4', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('T-MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VODAFONE', 100, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CLARO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('RCS & RDS', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MEGAFON', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELE2', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ETISALAT (MOBILY)', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SERBIA TELEKOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIP MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CABLE & WIRELESS', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MOBILE ONE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SINGTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA O2', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SI MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('CELL C', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTN', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('SK TELECOM', 50, 'USD', 'per SIM ');
insert into T_PAYMENT_THRESHOLD values ('MTN', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('YOIGO', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ETISALAT', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('HI3G ACCESS AB', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELE 2', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('FAR EASTONE', 70, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('T STAR', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TACOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AIS', 50, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('DTAC', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TRUE MOVE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELKOMSEL', 50, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TOGO CELLULAIRE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORANGE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ORASCOM', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AVEA', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TMC', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AFRICELL', 50, 'SDR', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AIRTEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('ASTELIT', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('KYIVSTAR', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MTS', 80, 'SDR', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('TELEFONICA', 50, 'USD', 'nan');
insert into T_PAYMENT_THRESHOLD values ('VODAFONE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('AT&T', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('LIMITLESS MOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('T-MOBILE', 50, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIAERO WIRELESS', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('UMS (MTS)', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('UNITEL', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('MOBIFONE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VIETNAMOBILE', 80, 'USD', 'total SIM');
insert into T_PAYMENT_THRESHOLD values ('VINAPHONE', 50, 'SDR', 'total SIM');
